name: Trigger n8n Deployment 22

on:
  registry_package:
    types: [published]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.registry_package.package_version.metadata.container.tags[0] != ''
    runs-on: self-hosted

    permissions:
      packages: read

    steps:

      - name: Get package version
        id: package
        run: |
          VERSION_ID="${{ github.event.registry_package.package_version.id }}"

          echo "Version ID: $VERSION_ID"

          TAG=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/user/packages/container/test_n8n/versions/$VERSION_ID \
            | jq -r '.metadata.container.tags[0]')

          echo "Tag trouvé: $TAG"

          if [ "$TAG" = "null" ] || [ -z "$TAG" ]; then
            echo "Aucun tag trouvé, arrêt du déploiement."
            exit 1
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT


      - name: Send webhook to n8n
        run: |
          TAG="${{ steps.package.outputs.tag }}"

          echo "📦 Déploiement du tag : $TAG"

          curl -X POST https://prescribe-whinny-species.ngrok-free.dev/webhook/deploy \
            -H "Content-Type: application/json" \
            -d "{\"tag\":\"$TAG\"}"

          echo "Webhook envoyé à n8n"