name: Trigger n8n Deployment

on:
  registry_package:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Debug event
        run: |
          echo '${{ toJson(github.event) }}'

      - name: Get tag
        id: get_tag
        run: |
          TAG="${{ github.event.package.package_version.metadata.container.tags[0] }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Send webhook to n8n
        run: |
          TAG="${{ steps.get_tag.outputs.tag }}"

          echo "📦 Déploiement du tag: $TAG"

          curl -X POST https://prescribe-whinny-species.ngrok-free.dev/webhook/deploy \
            -H "Content-Type: application/json" \
            -d '{
              "tag": "'"$TAG"'"
            }'

          echo "Webhook envoyé à n8n"