name: Trigger n8n Deployment

on:
  repository_dispatch:
    types: [docker-image-published]

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Send webhook to n8n
        run: |
          TAG="${{ github.event.client_payload.tag }}"

          echo "📦 Déploiement du tag : $TAG"

          curl -X POST http://localhost:5678/webhook/deploy \
            -H "Content-Type: application/json" \
            -d "{\"tag\":\"$TAG\"}"

          echo "Webhook envoyé à n8n"